### ISSUE TITLE
Experience running this on a regular Linux PC

### ISSUE THREAD

**Issue by wjoe** [shingonati0n/xivomega#1]
I came across this via some links in the issues on XivMitmLatencyMitigator. I'm playing FFXIV on a regular Linux distro, via XIVLauncher, and that project seemed overly complicated for just running the program on the same machine that I'm playing the game on.

Of course this project is more Steam Deck focused, but I saw your comment that it should work on regular Linux in some form, so I gave it a shot.

TL;DR is, yes, it does work, after some issues and edits to the script.

Firstly there's some hard coded file paths in the script, so I changed those to point to the directory I'm running it from (I didn't bother running the installer since that seemed like it'd be even more Deck specific, I just executed python run.py). This was changing the `pth` variable as well as line 22 which is also using the hard coded path.

Then there were errors regarding podman, as expected, so I installed it. Didn't do anything else with configuring it.

Then I replaced all of the wlan0 references with my device. This was easily enough accomplished with `sed -i s/wlan0/enp6s0/g` for my ethernet adaptor.

Then I went and ran it, and the output looked happy, so I launched the game.

On trying to connect to the data center in game, there was some output that indicated it was doing something, but there was an error, and then the game itself got a 2002 error and failed to connect

```
2024-11-16 18:22:46,754	58	INFO	New[game.JP.2024.11.06.0000.0000.json] ('10.88.0.7', 26395) ('10.88.0.1', 37066) ('204.2.29.7', 54994)
2024-11-16 18:22:49,756	58	INFO	Closed, exception occurred: <class 'TimeoutError'> timed out
Traceback (most recent call last):
  File "/home/mitm.py", line 1798, in run
    self.upstream.connect((str(self.destination[0]), self.destination[1]))
```

I'd also noticed that when launching XIVLauncher it had brought up the screen that it does when running it on the Deck, saying to switch back to the home screen and switch to the game and such. I didn't think much of it at first since the game still launched, it just hung out there in the background. But on subsequent launches, it was now telling me I needed to install the XIV free trial on Steam. Seemingly *something* had made it think I'm launching it on a Steam Deck now, but I'm not sure how, a quick scan of the script doesn't seem to be touching any files in XIVLauncher.

I ended up reinstalling XIVLauncher and now it seems to be back to normal. And now I launch the game, it connects just fine, and I can tell that it is working since I'm able to double weave again with my high latency in game.

This isn't necessarily a suggestion of changes or anything, mostly just recording my experience for anyone else who comes across this later and wants to give it a try. I may look into making some changes to make it flexible, but I wouldn't want to impact it's main intention of being a tool to run on the Steam Deck.

Anyway, thanks for this tool! Admittedly, I'm only really looking into this right now since Dalamud plugins are broken and will probably go back to NoClippy for the simplicity of it later, but right now this seems to be the easiest way to get latency mitigation working on Linux.

**Comment by RoarkGit** [comment]
I ran through the exact same steps you did independently and found it worked for me as well. The one annoyance was that I couldn't get the Steam Deck prompt to go away. I reinstalled XIVLauncher, cleared configs, etc. but couldn't get rid of it. Setting `XL_DECK=0` as a parameter can fix it, but I'd like to figure out what actually triggers this since repurposing the existing script for a generic Linux install is otherwise very straightforward. I ended up doing a btrfs snapshot restore to properly fix it, so I might attempt to use the script again and run a diff to see what actually changes.

**Comment by shingonati0n** [comment]
Thanks for the feedback - I'll be updating this soon with some of what you mentioned and will also introduce some things I've put in place in the plugin version (auto select ip from network and compatibility with Ethernet)

**Comment by shingonati0n** [comment]
Hello again @RoarkGit @wjoe, just pushed v.1.1.0 which should fix the hardcoded stuff you encountered. I've also updated the readme part to be more oriented to Linux. I tested this on my laptop running debian 12. Let me know how it goes. Thanks  again!

**Comment by RoarkGit** [comment]
I ran it again, the network adapter detection worked well. There were occasional segfaults with trying to find /home/mitm.py but I didn't get a chance to look closely at that yet. It does still cause XIVLauncher to think that it's running on a Steam Deck, but I haven't had a chance to look closely at that yet either. Do any of the IP routes correspond to Steam servers maybe and that's why it thinks it's running on a Steam Deck?

**Comment by shingonati0n** [comment]
I was start to look into that,and no, the ip routes are the same ones used in XivMitmLatencyMitigator, so it must be something else?? I'll report back once I found more about it. Does this happen only with XIVLauncher???

**Comment by wjoe** [comment]
@shingonati0n Looks good, thanks! A minor suggestion, it would be useful if it printed out which network adaptor it's using, and maybe a command line option to specify one manually. I have 2 ethernet adaptors which are both connected, and it seems like it might be luck that it hit the desired adaptor first in the loop.

@RoarkGit Do you have a `/home/deck` directory? Previously this was created by the XIVOmega container storage, and XIVLauncher explicitly checks if that directory exists. It looks like the config here has changed now so those files are created elsewhere, but you might still have the directory from the previous version.

**Comment by shingonati0n** [comment]
Hi @wjoe , I've followed your suggestion and put something to pick the network adapter when more than one is present and active, as in your scenario. The name of the adapter is also displayed at startup too. I've commited and pushed the changes, but haven't created the release package yet, mind testing it?? I'm not able to test due to not being able to connect to 2 different networks via cable at my home. Once you let me know it's working OK, I'll push the release. Thanks again for all the feedback!

**Comment by wjoe** [comment]
@shingonati0n It did show the two available ethernet adapters, but it gave an error after selecting one:

```
More than one Ethernet adapter has been detected - Please choose one now to proceed: 
To avoid picking everytime, you can save the name of your preferred adapter into config.ini in this folder
Detected Ethernet Adapters: 
1 - enp6s0
2 - enp7s0
Enter the number of the adapter you would like to use: 1
Terminating Mitigation Protocol and XIVOmega
Traceback (most recent call last):
  File "/home/joe/Programs/xivomega/run.py", line 417, in __main__
    ipv4 = os.popen('ip addr show ' + netdev).read().split("inet ")[1].split(" brd")[0] 
                    ~~~~~~~~~~~~~~~~^~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joe/Programs/xivomega/run.py", line 591, in <module>
    exit(__main__())
         ^^^^^^^^^^
  File "/home/joe/Programs/xivomega/run.py", line 587, in __main__
    omegaBeetle.SelfDestructProtocol()
  File "/home/joe/Programs/xivomega/run.py", line 180, in SelfDestructProtocol
    nav = subprocess.run(shlex.split(way),check=True,capture_output=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ip', 'route', 'del', '124.150.157.0/24', 'via', '10.88.0.7']' returned non-zero exit status 2.
```

It still works ok with only a single ethernet adapter available, so I could just disable the second one and ti worked then.

I'll do some poking tomorrow and see if I can work out the problem/fix.

**Comment by RoarkGit** [comment]
> @RoarkGit Do you have a `/home/deck` directory? Previously this was created by the XIVOmega container storage, and XIVLauncher explicitly checks if that directory exists. It looks like the config here has changed now so those files are created elsewhere, but you might still have the directory from the previous version.

Nope, no `/home/deck` directory so I'm not sure why it still does the check.

**Comment by shingonati0n** [comment]
> @shingonati0n It did show the two available ethernet adapters, but it gave an error after selecting one:
> 
> ```
> More than one Ethernet adapter has been detected - Please choose one now to proceed: 
> To avoid picking everytime, you can save the name of your preferred adapter into config.ini in this folder
> Detected Ethernet Adapters: 
> 1 - enp6s0
> 2 - enp7s0
> Enter the number of the adapter you would like to use: 1
> Terminating Mitigation Protocol and XIVOmega
> Traceback (most recent call last):
>   File "/home/joe/Programs/xivomega/run.py", line 417, in __main__
>     ipv4 = os.popen('ip addr show ' + netdev).read().split("inet ")[1].split(" brd")[0] 
>                     ~~~~~~~~~~~~~~~~^~~~~~~~
> TypeError: can only concatenate str (not "NoneType") to str
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/joe/Programs/xivomega/run.py", line 591, in <module>
>     exit(__main__())
>          ^^^^^^^^^^
>   File "/home/joe/Programs/xivomega/run.py", line 587, in __main__
>     omegaBeetle.SelfDestructProtocol()
>   File "/home/joe/Programs/xivomega/run.py", line 180, in SelfDestructProtocol
>     nav = subprocess.run(shlex.split(way),check=True,capture_output=True)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['ip', 'route', 'del', '124.150.157.0/24', 'via', '10.88.0.7']' returned non-zero exit status 2.
> ```
> 
> It still works ok with only a single ethernet adapter available, so I could just disable the second one and ti worked then.
> 
> I'll do some poking tomorrow and see if I can work out the problem/fix.

hey @wjoe I've fixed this exception (was caused because the input value when you pick the adapter was being read as str instead of int) and pushed the change. Please try it again and let me know if it works so I can push the new release. Thanks for all the help!

**Comment by wjoe** [comment]
@shingonati0n Sorry, I didn't see the message before. It does work now, although it prompts me to select the ethernet adapter twice.

If I set the ethernet adapter in the config.ini as suggested in the prompt, it only asks me once.

**Comment by shingonati0n** [comment]
@wjoe  do you by chance have both ethernets plus wifi connected?? or just ethernet?? I think it's related to that. When debugging I simulated being connected to 2 wifi and only had to pick one.

**Comment by wjoe** [comment]
2 ethernets connected, wifi is present but disabled/not connected.

```
More than one Ethernet adapter has been detected - Please choose one now to proceed: 
To avoid picking everytime, you can save the name of your preferred adapter into config.ini in this folder
Detected Ethernet Adapters: 
1 - enp6s0
2 - enp7s0
Enter the number of the adapter you would like to use: 1
IPs in use:
Chosen IPs:
VlanIP: 192.168.0.47
Last IP: 192.168.0.250
Welcome to XIVOmega v.0.01a
Network Adapter in use: enp6s0
podman ipvlan network xivlanc has been created
More than one Ethernet adapter has been detected - Please choose one now to proceed: 
To avoid picking everytime, you can save the name of your preferred adapter into config.ini in this folder
Detected Ethernet Adapters: 
1 - enp6s0
2 - enp7s0
Enter the number of the adapter you would like to use: 1
host ipvlan interface created
host ipvlan interface IP is 192.168.0.47
host ipvlan interface is up
Creating podman container
podman container created successfully
hooked to podman ipvlan network
```

**Comment by shingonati0n** [comment]
> 2 ethernets connected, wifi is present but disabled/not connected.
> 
> ```
> More than one Ethernet adapter has been detected - Please choose one now to proceed: 
> To avoid picking everytime, you can save the name of your preferred adapter into config.ini in this folder
> Detected Ethernet Adapters: 
> 1 - enp6s0
> 2 - enp7s0
> Enter the number of the adapter you would like to use: 1
> IPs in use:
> Chosen IPs:
> VlanIP: 192.168.0.47
> Last IP: 192.168.0.250
> Welcome to XIVOmega v.0.01a
> Network Adapter in use: enp6s0
> podman ipvlan network xivlanc has been created
> More than one Ethernet adapter has been detected - Please choose one now to proceed: 
> To avoid picking everytime, you can save the name of your preferred adapter into config.ini in this folder
> Detected Ethernet Adapters: 
> 1 - enp6s0
> 2 - enp7s0
> Enter the number of the adapter you would like to use: 1
> host ipvlan interface created
> host ipvlan interface IP is 192.168.0.47
> host ipvlan interface is up
> Creating podman container
> podman container created successfully
> hooked to podman ipvlan network
> ```

hi @wjoe I managed to fix this too. I had a redundant call to the method that gets the device, hence why you are getting the prompt twice. Please try it now. Thanks for the help!

**Comment by wjoe** [comment]
Looks good now @shingonati0n, it just asks me once, and doesn't ask me if I set it in the config. Thanks!

**Comment by shingonati0n** [comment]
Thanks for the help @wjoe ! v1.1.1 has been posted. If nothing else stands, I'll close this issue as complete. Let me know if there's any more feedback. Thanks again!
